name: DrestoriamSupport
version: ${project.version}
main: com.drestoriam.drestoriamsupport.DrestoriamSupport
api-version: 1.21.1
authors: [AlexxSGames, billbominecraft]
description: A support plugin for Drestoriam!
depend: [MCore]
commands:
  support:
    description: Main plugin command.
