name: MordoniaSupport
version: ${project.version}
main: com.mordonia.mordoniasupport.MordoniaSupport
api-version: 1.21.1
author: AlexxSGames
authors: [billbominecraft]
description: A support plugin for Mordonia!
website: mordoniamc.com
depend: [MCore]
commands:
  support:
    description: Main plugin command.
